services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server
    env_file:
      - ./server/.env
    depends_on:
      db:
        condition: service_healthy  # Wait for database to be ready

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pa55w.rd
      POSTGRES_DB: movies_db
      PGUSER: postgres
      PGPORT: 5435
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5435:5435"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    env_file:
      - ./frontend/.env
  

volumes:
  postgres_data:
