FROM python:3.13

WORKDIR /server

RUN apt-get update && apt-get install -y libpq-dev

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . . 

EXPOSE 8000

# CMD ["python","creat_tables.py"]
CMD [ "uvicorn" , "main:app",  "--reload" , "--host", "0.0.0.0", "--port", "8000"]



